version: '3'

services:
  django:
    build:
      context: .
    volumes:
      - uwsgi_data:/tmp/shm
    command: uwsgi -i /usr/src/app/uwsgi_sock.ini

  reverse_proxy:
    image: nginx:1.21.6-alpine
    ports:
      - "8001:9901"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf
      - uwsgi_data:/tmp/shm
    depends_on:
      - django

volumes:
  uwsgi_data:
