# Generated by Django 3.2.10 on 2022-03-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customernumber', models.IntegerField(db_column='customerNumber', primary_key=True, serialize=False)),
                ('customername', models.CharField(db_column='customerName', max_length=50)),
                ('contactlastname', models.CharField(db_column='contactLastName', max_length=50)),
                ('contactfirstname', models.CharField(db_column='contactFirstName', max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('addressline1', models.CharField(db_column='addressLine1', max_length=50)),
                ('addressline2', models.CharField(blank=True, db_column='addressLine2', max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postalcode', models.CharField(blank=True, db_column='postalCode', max_length=15, null=True)),
                ('country', models.CharField(max_length=50)),
                ('creditlimit', models.DecimalField(blank=True, db_column='creditLimit', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
    ]
