# Generated by Django 3.2.10 on 2022-03-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'managed': True},
        ),
    ]
